### ISSUE TITLE
Coherence Value for Every Topic is the Same

### ISSUE THREAD

**Issue by syed-razi** [myrithok/James#57]
### Description:
I'm noticing that every topic in the analysis has the same coherence value of `1.0000889005818406e-12` which does not seem to be correct

### Environment:
Device: Macbook Pro 2015
Browser: Chrome

### Steps to Reproduce:
1. Click "Drop files..." button
2. Upload the following file: [Computer Networking.txt](https://github.com/myrithok/James/files/6095966/Computer.Networking.txt)
### Actual Result:

When uploading this file I see:

![image](https://user-images.githubusercontent.com/25377291/110218777-857b4600-7e89-11eb-9e16-2eee3780e0d9.png)

### Expected Result:

I would expect to see different coherence values for different topics

**Comment by myrithok** [comment]
Thank you for the feedback! So the coherence scores were actually working correctly for you (most inputs did not result in all topics having the same coherence score), but while double-checking our coherence score values in order to respond to this issue, we discovered there was a much better way to implement our coherence scores! This has been implemented in commit 185691063c3dd37298387ed71d6efed8d0644913. Additionally, we've added information about coherence score calculation to the description in commit 2da150337e5266f7b18c6554bd9a92e7bbff4b19
