### ISSUE TITLE
Inconsistent/Incorrect lemmatization of Words

### ISSUE THREAD

**Issue by syed-razi** [myrithok/James#67]
### Description:
I uploaded a text file which contained different inflexions of words hoping that only the lemma would be captured, however this did not seem be consistent in all cases. It seems that when given a list of different inflexions, the first word in the same group is chosen rather than the lemma, and sometimes multiple words are chosen which should have been omitted. This relates to the data preprocessing functional requirement 3-2-7

### Environment:
Device: Macbook Pro 2015
Browser: Chrome

### Steps to Reproduce:
1. Click "Drop files..." button
2. Upload the following file:  [Testing Lemmatization.txt](https://github.com/myrithok/James/files/6096234/Testing.Lemmatization.txt)

### Actual Result:

I've noted the discrepencies I've seen in the image below:

![image](https://user-images.githubusercontent.com/25377291/110222748-7d7bd000-7ea2-11eb-9937-e6a92f6774c3.png)

As you can see, in the text file, for the list of words `argued argues arguing argue`, the first word `argued` is chosen rather than the lemma `argue`. Sometimes multiple words are chosen when only one should be chosen, for example how `fruits` and `fruity` is chosen over the expected lemma `fruit`. In the list containing different word forms for `operate`, `operate` is correctly chosen, however it seems that this is because it is the first word in the list rather than it being the lemma.

### Expected Result:

I would expect the correct lemma of a word to be chosen when given a list of similar word forms. I would also expect only one word to be chosen, as opposed to many.

**Comment by myrithok** [comment]
Thank you for the feedback! The lemmatization was actually working correctly; we had decided to show example words to the user, rather than the stems, to make the results a little bit more intelligible. Each stem was represented in the results by the first occurrence of a word that produced that stem while lemmatizing the input. However, we never communicated that to the user, which understandably produced confusing results. 

So, we have added the word stems in addition to the example word in commit 6b59aeec2559ca4beff6f788457de17698615363, which looks like this:

![image](https://user-images.githubusercontent.com/32877366/112549931-f4ff9980-8d94-11eb-9301-fa1c71381868.png)

We will also clarify this in the instructions on the homepage soon.
